### PR TITLE
Prevent usage of the old JUnit version (4.11)

### PR DESCRIPTION
**Pull request by vbauer**
Duplicated declarations of JUnit library were also removed
It is declared in the root pom.xml

### CODE REVIEW

**Review by savageautomate — COMMENTED** [review]
Should the ```<scope>test</scope>``` be left in place?  To limit this dependency to testing and not a runtime dependency?

**Comment by vbauer** [comment]
As I see, it is configured in dependency management section, so it should be unnecessary

**Comment by savageautomate** [comment]
@vbauer 

I don't think it is.  I think its in global shared dependencies from the parent POM.
We could move it to dependency management and then we could add a reference in each project's POM  that needs it.

**Comment by vbauer** [comment]
I mean that junit has test scope and it could be checked simple using Maven dependency tree:
```
➜  pi4j git:(remove-old-junit) mvn dependency:tree
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.pi4j:pi4j-core:jar:1.2-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-surefire-plugin is missing. @ com.pi4j:pi4j-core:[unknown-version], /Users/vbauer/Documents/workspace/java/pi4j/pi4j-core/pom.xml, line 66, column 12
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] Pi4J :: Parent POM
[INFO] Pi4J :: Java Library (Core)
[INFO] Pi4J :: GPIO Extension
[INFO] Pi4J :: Device Abstractions
[INFO] Pi4J :: Java Examples
[INFO] Pi4J :: Distribution
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Pi4J :: Parent POM 1.2-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-dependency-plugin:2.10:tree (default-cli) @ pi4j-parent ---
[INFO] com.pi4j:pi4j-parent:pom:1.2-SNAPSHOT
[INFO] \- junit:junit:jar:4.12:test
[INFO]    \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Pi4J :: Java Library (Core) 1.2-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-dependency-plugin:2.10:tree (default-cli) @ pi4j-core ---
[INFO] com.pi4j:pi4j-core:jar:1.2-SNAPSHOT
[INFO] +- com.pi4j:pi4j-native:so:raspberrypi-static:1.2-SNAPSHOT:provided
[INFO] +- org.mockito:mockito-all:jar:1.10.19:test
[INFO] +- org.powermock:powermock-module-junit4:jar:1.6.5:test
[INFO] |  \- org.powermock:powermock-module-junit4-common:jar:1.6.5:test
[INFO] |     +- org.powermock:powermock-core:jar:1.6.5:test
[INFO] |     |  \- org.javassist:javassist:jar:3.20.0-GA:test
[INFO] |     \- org.powermock:powermock-reflect:jar:1.6.5:test
[INFO] +- org.powermock:powermock-api-mockito:jar:1.6.5:test
[INFO] |  +- org.mockito:mockito-core:jar:1.10.19:test
[INFO] |  |  \- org.objenesis:objenesis:jar:2.1:test
[INFO] |  +- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] |  \- org.powermock:powermock-api-mockito-common:jar:1.6.5:test
[INFO] |     \- org.powermock:powermock-api-support:jar:1.6.5:test
[INFO] \- junit:junit:jar:4.12:test
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Pi4J :: GPIO Extension 1.2-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-dependency-plugin:2.10:tree (default-cli) @ pi4j-gpio-extension ---
[INFO] com.pi4j:pi4j-gpio-extension:jar:1.2-SNAPSHOT
[INFO] +- com.pi4j:pi4j-core:jar:1.2-SNAPSHOT:compile
[INFO] +- org.jmockit:jmockit:jar:1.9:test
[INFO] \- junit:junit:jar:4.12:test
[INFO]    \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Pi4J :: Device Abstractions 1.2-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-dependency-plugin:2.10:tree (default-cli) @ pi4j-device ---
[INFO] com.pi4j:pi4j-device:jar:1.2-SNAPSHOT
[INFO] +- com.pi4j:pi4j-core:jar:1.2-SNAPSHOT:compile
[INFO] +- com.pi4j:pi4j-gpio-extension:jar:1.2-SNAPSHOT:compile
[INFO] +- org.mockito:mockito-all:jar:1.10.19:test
[INFO] \- junit:junit:jar:4.12:test
[INFO]    \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Pi4J :: Java Examples 1.2-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: https://oss.sonatype.org/content/groups/public/com/pi4j/pi4j-device/1.2-SNAPSHOT/maven-metadata.xml
Downloaded: https://oss.sonatype.org/content/groups/public/com/pi4j/pi4j-device/1.2-SNAPSHOT/maven-metadata.xml (2 KB at 0.9 KB/sec)
Downloading: https://oss.sonatype.org/content/groups/public/com/pi4j/pi4j-core/1.2-SNAPSHOT/maven-metadata.xml
Downloaded: https://oss.sonatype.org/content/groups/public/com/pi4j/pi4j-core/1.2-SNAPSHOT/maven-metadata.xml (3 KB at 5.4 KB/sec)
Downloading: https://oss.sonatype.org/content/groups/public/com/pi4j/pi4j-gpio-extension/1.2-SNAPSHOT/maven-metadata.xml
Downloaded: https://oss.sonatype.org/content/groups/public/com/pi4j/pi4j-gpio-extension/1.2-SNAPSHOT/maven-metadata.xml (2 KB at 4.8 KB/sec)
[INFO]
[INFO] --- maven-dependency-plugin:2.10:tree (default-cli) @ pi4j-example ---
[INFO] com.pi4j:pi4j-example:jar:1.2-SNAPSHOT
[INFO] +- com.pi4j:pi4j-core:jar:1.2-SNAPSHOT:compile
[INFO] +- com.pi4j:pi4j-gpio-extension:jar:1.2-SNAPSHOT:compile
[INFO] +- com.pi4j:pi4j-device:jar:1.2-SNAPSHOT:compile
[INFO] \- junit:junit:jar:4.12:test
[INFO]    \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Pi4J :: Distribution 1.2-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-dependency-plugin:2.10:tree (default-cli) @ pi4j-distribution ---
[INFO] com.pi4j:pi4j-distribution:deb:1.2-SNAPSHOT
[INFO] +- com.pi4j:pi4j-core:jar:1.2-SNAPSHOT:compile
[INFO] +- com.pi4j:pi4j-core:jar:sources:1.2-SNAPSHOT:compile
[INFO] +- com.pi4j:pi4j-core:jar:javadoc:1.2-SNAPSHOT:compile
[INFO] +- com.pi4j:pi4j-device:jar:1.2-SNAPSHOT:compile
[INFO] +- com.pi4j:pi4j-device:jar:sources:1.2-SNAPSHOT:compile
[INFO] +- com.pi4j:pi4j-device:jar:javadoc:1.2-SNAPSHOT:compile
[INFO] +- com.pi4j:pi4j-gpio-extension:jar:1.2-SNAPSHOT:compile
[INFO] +- com.pi4j:pi4j-gpio-extension:jar:sources:1.2-SNAPSHOT:compile
[INFO] +- com.pi4j:pi4j-gpio-extension:jar:javadoc:1.2-SNAPSHOT:compile
[INFO] +- com.pi4j:pi4j-example:jar:1.2-SNAPSHOT:compile
[INFO] +- com.pi4j:pi4j-example:jar:sources:1.2-SNAPSHOT:compile
[INFO] +- com.pi4j:pi4j-example:jar:javadoc:1.2-SNAPSHOT:compile
[INFO] \- junit:junit:jar:4.12:test
[INFO]    \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Pi4J :: Parent POM ................................. SUCCESS [  2.384 s]
[INFO] Pi4J :: Java Library (Core) ........................ SUCCESS [  0.985 s]
[INFO] Pi4J :: GPIO Extension ............................. SUCCESS [  0.011 s]
[INFO] Pi4J :: Device Abstractions ........................ SUCCESS [  0.011 s]
[INFO] Pi4J :: Java Examples .............................. SUCCESS [  3.307 s]
[INFO] Pi4J :: Distribution ............................... SUCCESS [  0.347 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 12.454 s
[INFO] Finished at: 2017-02-10T23:40:33+06:00
[INFO] Final Memory: 30M/295M
[INFO] ------------------------------------------------------------------------
```

As we can see all junit dependencies in test scope

Global dependency of junit is included in the parent pom without scope and version:
```
    <!-- GLOBAL DEPENDENCIES -->
    <dependencies>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
        </dependency>
    </dependencies>
```

**Comment by savageautomate** [comment]
Sweet! I did not realize it was inherently scoped to test.    Thanks for pointing that out.  Merging now.

**Comment by vbauer** [comment]
Thank you for merge!

**Pull request merged**
